In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("../../data/diabetes_prediction_dataset.csv")

df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   gender               100000 non-null  object
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64
 3   heart_disease        100000 non-null  int64
 4   smoking_history      100000 non-null  object
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64
 8   diabetes             100000 non-null  int64
dtypes: float64(3), int64(4), object(2)
memory usage: 6.9+ MB

In [4]:
df.describe()

,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,diabetes
count,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,41.885856,0.07485,0.039420,27.320767,5.527507,138.058060,0.085000
std,22.516840,0.26315,0.194593,6.636783,1.070672,40.708136,0.278883
min,0.080000,0.00000,0.000000,10.010000,3.500000,80.000000,0.000000
25%,24.000000,0.00000,0.000000,23.630000,4.800000,100.000000,0.000000
50%,43.000000,0.00000,0.000000,27.320000,5.800000,140.000000,0.000000
75%,60.000000,0.00000,0.000000,29.580000,6.200000,159.000000,0.000000
max,80.000000,1.00000,1.000000,95.690000,9.000000,300.000000,1.000000

In [5]:
df.shape

(100000, 9)

In [6]:
df.duplicated().sum()

np.int64(3854)

In [7]:
df = df.drop_duplicates()
df

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0
...,...,...,...,...,...,...,...,...,...
99994,Female,36.0,0,0,No Info,24.60,4.8,145,0
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0
99998,Female,24.0,0,0,never,35.42,4.0,100,0
99999,Female,57.0,0,0,current,22.43,6.6,90,0

In [8]:
df.columns = df.columns.str.lower()

In [9]:
df['age'].sort_values(ascending=True)

13162     0.08
40039     0.08
92964     0.08
93847     0.08
67326     0.08
         ...
45784    80.00
45757    80.00
74736    80.00
74686    80.00
99984    80.00
Name: age, Length: 96146, dtype: float64

## Age

In [10]:
df =  df[(df['age']  > 1 ) ]

In [11]:
df['age'] = df['age'].astype(int)

C:\Users\dunsin\AppData\Local\Temp\ipykernel_11508\2037022551.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['age'] = df['age'].astype(int)

## Gender

In [18]:
df['gender'].value_counts()

gender
Female    55679
Male      39456
Other        18
Name: count, dtype: int64

In [15]:
df[df['gender'] == 'Other']

,gender,age,hypertension,heart_disease,smoking_history,bmi,hba1c_level,blood_glucose_level,diabetes
12669,Other,10,0,0,not current,14.09,5.0,140,0
14838,Other,19,0,0,No Info,27.32,5.7,158,0
16702,Other,39,0,0,not current,31.24,6.2,85,0
18691,Other,10,0,0,not current,16.59,6.1,160,0
23266,Other,23,0,0,No Info,24.23,6.1,140,0
31985,Other,53,0,0,No Info,27.32,6.6,160,0
33805,Other,45,0,0,never,27.32,4.0,159,0
34929,Other,47,0,0,never,36.76,6.6,90,0
35006,Other,47,0,0,never,36.76,3.5,200,0
40337,Other,18,0,0,not current,30.19,6.1,90,0
56238,Other,10,0,0,not current,19.75,6.1,126,0
66595,Other,55,0,0,No Info,27.32,5.0,158,0
66887,Other,19,0,0,No Info,27.32,3.5,160,0
67204,Other,7,0,0,No Info,27.32,3.5,159,0
68484,Other,52,0,0,not current,31.63,6.6,159,0
71139,Other,28,0,0,ever,27.32,4.5,126,0
75302,Other,26,0,0,not current,37.49,6.0,80,0
75734,Other,24,0,0,not current,22.86,6.2,160,0

In [16]:
df['gender'].isna().sum()

np.int64(0)

## Hypertension

In [21]:
df['hypertension'].unique()

array([0, 1])

In [22]:
df['hypertension'].value_counts()

hypertension
0    87692
1     7461
Name: count, dtype: int64

In [24]:
df['hypertension'].isna().sum()

np.int64(0)

## heart_disease

In [28]:
df['heart_disease'].value_counts()

heart_disease
0    91230
1     3923
Name: count, dtype: int64

In [29]:
df['heart_disease'].isna().sum()

np.int64(0)

## smoking_history

In [31]:
df['smoking_history'].unique()

array(['never', 'No Info', 'current', 'former', 'ever', 'not current'],
      dtype=object)

In [33]:
df['smoking_history'].value_counts()

smoking_history
never          34357
No Info        31945
former          9299
current         9196
not current     6358
ever            3998
Name: count, dtype: int64

In [35]:
df[df['smoking_history'] == 'ever']

,gender,age,hypertension,heart_disease,smoking_history,bmi,hba1c_level,blood_glucose_level,diabetes
19,Male,37,0,0,ever,25.72,3.5,159,0
65,Female,59,0,1,ever,23.11,6.5,200,0
88,Female,38,0,0,ever,22.42,6.0,85,0
103,Female,55,0,0,ever,18.60,6.0,160,0
156,Female,54,0,0,ever,26.72,6.1,158,0
...,...,...,...,...,...,...,...,...,...
99895,Male,74,0,0,ever,27.32,3.5,85,0
99949,Female,26,0,0,ever,21.50,6.5,160,0
99953,Female,59,1,0,ever,60.52,3.5,158,0
99956,Male,26,0,0,ever,25.60,6.6,90,0
99970,Male,32,0,0,ever,37.71,6.1,126,0