In [36]:
import pandas as pd 
import numpy as np

In [37]:
df = pd.read_csv("../../data/cardio_data_processed.csv")
df.head()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,age_years,bmi,bp_category,bp_category_encoded
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0,50,21.967120,Hypertension Stage 1,Hypertension Stage 1
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1,55,34.927679,Hypertension Stage 2,Hypertension Stage 2
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1,51,23.507805,Hypertension Stage 1,Hypertension Stage 1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1,48,28.710479,Hypertension Stage 2,Hypertension Stage 2
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0,47,23.011177,Normal,Normal

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68205 entries, 0 to 68204
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   68205 non-null  int64
 1   age                  68205 non-null  int64
 2   gender               68205 non-null  int64
 3   height               68205 non-null  int64
 4   weight               68205 non-null  float64
 5   ap_hi                68205 non-null  int64
 6   ap_lo                68205 non-null  int64
 7   cholesterol          68205 non-null  int64
 8   gluc                 68205 non-null  int64
 9   smoke                68205 non-null  int64
 10  alco                 68205 non-null  int64
 11  active               68205 non-null  int64
 12  cardio               68205 non-null  int64
 13  age_years            68205 non-null  int64
 14  bmi                  68205 non-null  float64
 15  bp_category          68205 non-null  object
 16  bp_category_encoded  68205 non-null  object
dtypes: float64(2), int64(13), object(2)
memory usage: 8.8+ MB

In [39]:
df.duplicated().sum()

np.int64(0)

In [40]:
df.isna().sum()

id                     0
age                    0
gender                 0
height                 0
weight                 0
ap_hi                  0
ap_lo                  0
cholesterol            0
gluc                   0
smoke                  0
alco                   0
active                 0
cardio                 0
age_years              0
bmi                    0
bp_category            0
bp_category_encoded    0
dtype: int64

In [41]:
df.describe(include='all')

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,age_years,bmi,bp_category,bp_category_encoded
count,68205.000000,68205.000000,68205.000000,68205.000000,68205.000000,68205.000000,68205.000000,68205.000000,68205.000000,68205.000000,68205.000000,68205.000000,68205.000000,68205.000000,68205.000000,68205,68205
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,4
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hypertension Stage 1,Hypertension Stage 1
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39750,39750
mean,49972.410498,19462.667737,1.348625,164.372861,74.100688,126.434924,81.263925,1.363243,1.225174,0.087662,0.053134,0.803548,0.493688,52.823635,27.510513,NaN,NaN
std,28852.138290,2468.381854,0.476539,8.176756,14.288862,15.961685,9.143985,0.678080,0.571288,0.282805,0.224302,0.397317,0.499964,6.769909,6.026497,NaN,NaN
min,0.000000,10798.000000,1.000000,55.000000,11.000000,90.000000,60.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,29.000000,3.471784,NaN,NaN
25%,24991.000000,17656.000000,1.000000,159.000000,65.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,48.000000,23.875115,NaN,NaN
50%,50008.000000,19700.000000,1.000000,165.000000,72.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,53.000000,26.346494,NaN,NaN
75%,74878.000000,21323.000000,2.000000,170.000000,82.000000,140.000000,90.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,58.000000,30.116213,NaN,NaN
max,99999.000000,23713.000000,2.000000,250.000000,200.000000,180.000000,120.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000,64.000000,298.666667,NaN,NaN

### Drop Unncessary column

In [42]:
df.drop(columns=["age", 'id'],inplace=True )

In [43]:
df.head()

,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,age_years,bmi,bp_category,bp_category_encoded
0,2,168,62.0,110,80,1,1,0,0,1,0,50,21.967120,Hypertension Stage 1,Hypertension Stage 1
1,1,156,85.0,140,90,3,1,0,0,1,1,55,34.927679,Hypertension Stage 2,Hypertension Stage 2
2,1,165,64.0,130,70,3,1,0,0,0,1,51,23.507805,Hypertension Stage 1,Hypertension Stage 1
3,2,169,82.0,150,100,1,1,0,0,1,1,48,28.710479,Hypertension Stage 2,Hypertension Stage 2
4,1,156,56.0,100,60,1,1,0,0,0,0,47,23.011177,Normal,Normal

### Gender

In [44]:
df["gender"] = df['gender'].replace(1,"F").replace(2,"M")

In [45]:
df["gender"].unique()

array(['M', 'F'], dtype=object)

In [46]:
df["gender"].value_counts()

gender
F    44427
M    23778
Name: count, dtype: int64

In [47]:
df["gender"].isna().sum()

np.int64(0)

## Height

In [48]:
df["height"].unique()

array([168, 156, 165, 169, 151, 157, 178, 158, 164, 173, 181, 172, 170,
       154, 162, 163, 153, 159, 166, 155, 160, 175, 171, 152, 187, 148,
       179, 180, 188, 185, 167, 183, 174, 176, 161, 184, 177, 182,  76,
       149, 142, 150, 144, 186, 147, 146, 141, 195, 140, 198, 145, 143,
       196, 138, 194, 190, 134, 136, 100, 120, 189, 137, 192, 122, 250,
       191, 117,  97, 119, 130, 110, 193,  75, 132,  71, 135,  67,  70,
       125, 139, 133,  74, 112, 207,  68,  55,  81,  80,  64,  91,  60,
       109,  72, 197,  65, 128, 105, 108, 111, 113,  96, 104, 131,  59,
        99,  57])

In [49]:
df["height"].value_counts()

height
165    5728
160    4890
170    4584
168    4307
164    3323
       ...
104       1
131       1
59        1
99        1
57        1
Name: count, Length: 106, dtype: int64

In [50]:
df["height"].isna().sum()

np.int64(0)

### weight

In [51]:
df["weight"].unique()

array([ 62.  ,  85.  ,  64.  ,  82.  ,  56.  ,  67.  ,  93.  ,  95.  ,
        71.  ,  68.  ,  80.  ,  60.  ,  78.  , 112.  ,  75.  ,  52.  ,
        83.  ,  69.  ,  90.  ,  45.  ,  65.  ,  59.  ,  66.  ,  74.  ,
       105.  ,  73.  ,  55.  ,  70.  ,  72.  ,  63.  ,  50.  , 107.  ,
        84.  ,  77.  ,  79.  ,  76.  ,  58.  , 115.  ,  97.  ,  53.  ,
        57.  ,  49.  , 110.  ,  94.  ,  92.  ,  87.  , 103.  ,  88.  ,
        99.  , 100.  ,  61.  ,  48.  ,  54.  ,  51.  ,  47.  ,  91.  ,
       104.  ,  81.  ,  98.  , 108.  ,  89.  , 101.  ,  86.  ,  65.5 ,
       142.  ,  96.  ,  44.  , 169.  , 116.  , 200.  ,  64.8 , 120.  ,
       117.  , 125.  , 106.  , 114.  , 113.  , 129.  , 124.  ,  42.  ,
       123.  , 111.  , 102.  , 109.  ,  46.  , 139.  , 150.  , 138.  ,
       131.  ,  43.  ,  83.6 , 134.  , 106.5 , 121.  ,  40.  , 141.  ,
       119.  , 126.  , 177.  , 165.  , 122.  ,  41.  ,  62.3 , 118.  ,
        89.5 , 132.  , 130.  , 159.  ,  84.6 , 140.  ,  82.3 ,  30.  ,
        67.9 , 127.  ,  67.5 ,  74.3 , 149.  , 180.  , 128.  ,  60.2 ,
        64.5 ,  58.7 ,  90.5 ,  37.  ,  80.8 , 166.  , 161.  ,  92.2 ,
        75.6 , 136.  ,  82.9 , 154.  ,  68.9 , 170.  ,  84.5 , 135.  ,
        72.5 , 146.  ,  70.5 ,  74.2 ,  84.3 ,  38.  ,  54.5 , 145.  ,
        68.5 ,  79.5 ,  72.8 ,  73.2 ,  96.5 ,  53.2 ,  39.  ,  61.2 ,
       168.  , 133.  ,  54.35,  50.7 ,  79.94, 153.  ,  34.  ,  62.4 ,
       167.  , 156.  ,  35.  ,  70.3 ,  31.  ,  60.5 ,  69.8 ,  64.7 ,
        64.1 , 152.  ,  59.5 , 163.  ,  75.5 ,  78.2 , 162.  , 121.3 ,
       178.  ,  82.5 ,  90.7 ,  55.6 ,  59.8 ,  32.  ,  70.8 ,  57.4 ,
        73.8 ,  56.2 ,  69.5 ,  71.5 ,  89.1 , 158.  ,  76.5 ,  35.45,
        86.5 ,  63.8 ,  23.  , 144.  ,  70.2 ,  68.4 , 148.  , 164.  ,
        22.  ,  66.5 ,  59.2 ,  65.3 , 137.  ,  62.2 ,  36.  ,  61.5 ,
        80.5 ,  81.1 ,  53.6 ,  11.  ,  66.4 ,  76.7 ,  28.  ,  68.3 ,
        60.6 ,  76.8 ,  58.8 ,  75.2 ,  83.5 ,  64.3 ,  84.9 ,  80.7 ,
        84.7 ,  60.1 , 105.5 ,  85.5 , 121.8 , 155.  ,  51.5 ,  53.9 ,
        42.2 ,  74.5 , 114.6 ,  73.5 ,  71.3 ,  33.  ,  66.3 ,  53.3 ,
        67.8 ,  70.7 ,  52.3 ,  82.4 ,  63.4 ,  71.2 ,  62.5 ,  63.82,
        88.5 ,  89.9 ,  72.1 , 106.4 , 160.  ,  68.2 ,  53.67, 171.  ,
        55.2 ,  94.5 , 143.  ,  62.7 ,  53.5 , 109.5 ,  82.1 ,  57.8 ,
        84.8 ,  21.  ,  29.  , 183.  ,  57.6 ,  78.5 , 172.  , 109.7 ,
        61.3 ,  67.3 ,  94.7 , 147.  ,  55.4 ,  99.9 ])

In [52]:
df["weight"].isna().sum()

np.int64(0)

In [53]:
df["weight"].value_counts()

weight
65.0     3779
70.0     3692
68.0     2767
75.0     2675
60.0     2670
         ...
67.3        1
94.7        1
147.0       1
55.4        1
99.9        1
Name: count, Length: 278, dtype: int64

### Ap_hi

In [54]:
df["ap_hi"].unique()

array([110, 140, 130, 150, 100, 120, 145, 170, 135, 125,  90, 180, 160,
       133, 122, 169, 126, 158, 123, 161, 147, 115, 137, 153, 148, 105,
       119, 141, 165, 164, 124, 172, 162, 117, 134, 166, 176, 116, 121,
       112, 113, 118, 155, 142, 157, 136, 146, 138, 131, 159, 109, 106,
       129,  93, 179,  95, 156, 168, 132, 104, 103, 175, 128, 151, 139,
       127, 108, 144, 102, 143, 107, 178, 149, 167, 114, 101, 171, 111,
       163, 154, 177, 174, 152,  96, 173,  99])

In [55]:
df["ap_hi"].value_counts()

ap_hi
120    27654
140     9324
130     8907
110     8617
150     4197
       ...
178        2
96         2
177        2
173        2
93         1
Name: count, Length: 86, dtype: int64

Ap_lo

In [56]:
df["ap_lo"].unique()

array([ 80,  90,  70, 100,  60,  85,  89, 110,  65,  63,  79, 120, 109,
        84,  91,  73,  78,  75,  86,  87,  82,  95,  69,  74,  97,  81,
        83, 119,  93, 105,  99,  77,  92, 108, 115,  68,  61, 106, 102,
        94,  66,  76,  62,  96, 113,  67,  88, 112, 104,  71,  72,  98,
       101,  64, 103, 114, 111, 107])

In [57]:
df["ap_lo"].value_counts()

ap_lo
80     34725
90     14239
70     10212
100     3978
60      2656
79       357
110      338
85       290
75       209
95       158
120      134
89       122
69        98
65        78
82        33
84        32
83        30
87        29
78        27
74        26
86        26
73        22
72        22
92        21
81        21
91        20
88        20
99        20
76        19
67        19
77        18
94        17
105       17
98        16
96        14
71        14
97        13
68        13
93        11
66        11
64        10
63         7
62         7
115        7
109        6
103        6
61         6
101        5
104        5
106        5
102        4
108        3
113        3
119        2
112        1
114        1
111        1
107        1
Name: count, dtype: int64

### cholesterol

In [58]:
df["cholesterol"].unique()

array([1, 3, 2])

In [59]:
df["cholesterol"].value_counts()

cholesterol
1    51222
2     9191
3     7792
Name: count, dtype: int64

### Gluc (glucose level )

In [60]:
df["gluc"].unique()

array([1, 2, 3])

In [61]:
df["gluc"].value_counts()

gluc
1    58027
3     5180
2     4998
Name: count, dtype: int64

### smoke

In [62]:
df["smoke"].unique()

array([0, 1])

In [63]:
df["smoke"].value_counts()

smoke
0    62226
1     5979
Name: count, dtype: int64

### alco

In [64]:
df["alco"].unique()

array([0, 1])

In [65]:
df["alco"].value_counts()

alco
0    64581
1     3624
Name: count, dtype: int64

### active

In [66]:
df["active"].unique()

array([1, 0])

In [67]:
df["active"].value_counts()

active
1    54806
0    13399
Name: count, dtype: int64

### cardio

In [68]:
df['cardio'].unique()

array([0, 1])

In [69]:
df['cardio'].value_counts()

cardio
0    34533
1    33672
Name: count, dtype: int64

In [88]:
df.drop('cardio',  axis = 1 , inplace= True )

### Age

In [70]:
df['age_years'].unique()

array([50, 55, 51, 48, 47, 60, 61, 54, 40, 39, 45, 58, 59, 63, 64, 53, 49,
       57, 56, 46, 43, 62, 52, 42, 44, 41, 29, 30])

In [71]:
df.rename( columns  =  {'age_years':'age' } , inplace=True)

In [74]:
df.head()

,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,age,bmi,bp_category,bp_category_encoded
0,M,168,62.0,110,80,1,1,0,0,1,0,50,21.967120,Hypertension Stage 1,Hypertension Stage 1
1,F,156,85.0,140,90,3,1,0,0,1,1,55,34.927679,Hypertension Stage 2,Hypertension Stage 2
2,F,165,64.0,130,70,3,1,0,0,0,1,51,23.507805,Hypertension Stage 1,Hypertension Stage 1
3,M,169,82.0,150,100,1,1,0,0,1,1,48,28.710479,Hypertension Stage 2,Hypertension Stage 2
4,F,156,56.0,100,60,1,1,0,0,0,0,47,23.011177,Normal,Normal

### bmi

In [78]:
df['bmi'].unique()

array([21.96712018, 34.92767916, 23.50780533, ..., 19.23018223,
       29.19412649, 50.47268066], shape=(3752,))

In [76]:
df['bmi'].value_counts()

bmi
23.875115    930
23.437500    641
24.221453    485
25.711662    359
22.038567    354
            ...
55.096419      1
47.417660      1
52.073001      1
32.215630      1
42.790865      1
Name: count, Length: 3752, dtype: int64

In [79]:
df['bmi'].isna().sum()

np.int64(0)

bp category

In [81]:
df['bp_category'].value_counts()

bp_category
Hypertension Stage 1    39750
Hypertension Stage 2    15937
Normal                   9417
Elevated                 3101
Name: count, dtype: int64

In [86]:
df

,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,age,bmi,bp_category
0,M,168,62.0,110,80,1,1,0,0,1,0,50,21.967120,Hypertension Stage 1
1,F,156,85.0,140,90,3,1,0,0,1,1,55,34.927679,Hypertension Stage 2
2,F,165,64.0,130,70,3,1,0,0,0,1,51,23.507805,Hypertension Stage 1
3,M,169,82.0,150,100,1,1,0,0,1,1,48,28.710479,Hypertension Stage 2
4,F,156,56.0,100,60,1,1,0,0,0,0,47,23.011177,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68200,M,168,76.0,120,80,1,1,1,0,1,0,52,26.927438,Hypertension Stage 1
68201,F,158,126.0,140,90,2,2,0,0,1,1,61,50.472681,Hypertension Stage 2
68202,M,183,105.0,180,90,3,1,0,1,0,1,52,31.353579,Hypertension Stage 2
68203,F,163,72.0,135,80,1,2,0,0,0,1,61,27.099251,Hypertension Stage 1
68204,F,170,72.0,120,80,2,1,0,0,1,0,56,24.913495,Hypertension Stage 1

### bp_category_encoded

In [85]:
df.drop(['bp_category_encoded'] ,  axis=1 , inplace = True)

In [89]:
df.head()

,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,age,bmi,bp_category
0,M,168,62.0,110,80,1,1,0,0,1,50,21.967120,Hypertension Stage 1
1,F,156,85.0,140,90,3,1,0,0,1,55,34.927679,Hypertension Stage 2
2,F,165,64.0,130,70,3,1,0,0,0,51,23.507805,Hypertension Stage 1
3,M,169,82.0,150,100,1,1,0,0,1,48,28.710479,Hypertension Stage 2
4,F,156,56.0,100,60,1,1,0,0,0,47,23.011177,Normal

save new data

In [90]:
df.to_csv("../../data/hyper.csv" ,  index=False)

### Load the data

In [91]:
p_df = pd.read_csv("../../data/hyper.csv")

In [93]:
p_df.head()

,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,age,bmi,bp_category
0,M,168,62.0,110,80,1,1,0,0,1,50,21.967120,Hypertension Stage 1
1,F,156,85.0,140,90,3,1,0,0,1,55,34.927679,Hypertension Stage 2
2,F,165,64.0,130,70,3,1,0,0,0,51,23.507805,Hypertension Stage 1
3,M,169,82.0,150,100,1,1,0,0,1,48,28.710479,Hypertension Stage 2
4,F,156,56.0,100,60,1,1,0,0,0,47,23.011177,Normal